.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH vtgammatest 1 2006-07-12 Debian "Linux console"
.SH NAME
vtgammatest \- interactively test monitor's required gamma correction
.SH SYNOPSIS
.B vtgammatest
.SH DESCRIPTION
This program can help you tell what gamma correction would be appropiate
for your monitor.  There are no command-line options, and the needed steps
are described within the program, so I won't repeat that here.

Be aware, though, that while
.B vtgamma
is fully functional on all types of Linux console and even a few other
terminal types,
.B vtgammatest
works accurately only on CRTs and native-resolution LCDs, and even then only
if your font uses reasonable glyphs for the test characters.

If in
.I any
doubt, use a graphical test.  Appropiate images can be found for example on
the right-hand side of the
.URL "http://en.wikipedia.org/wiki/Gamma_correction" "Wikipedia article" .
Squint and/or step away from the monitor, the image which appears to be of
the same brightness on both left and right halves will show you the value
you need.  If you already use
.BR xgamma ,
or a similar tool, you will have to multiply the result by the gamma value
you have already set.

.SH "SEE ALSO"
.IR vtgamma ( 1 "), " xgamma ( 1 ).
.SH AUTHOR
Both the program and this man page are the fault of Adam Borowski.  Both of
them are in the Public Domain, or the closest approximation allowed by law.
