.TH vtgamma 1 2006-07-10 Debian "Linux console"
.SH NAME
vtgamma \- set gamma correction on text terminals
.SH SYNOPSIS
.B vtgamma
.RI [ -e ] " " [ -r ] " " [ -l ] " <gamma>"
.br
.B vtgamma
.RI [ -e ] " " [ -r ] " <red gamma> <green gamma> <blue gamma>"
.br
.B vtgamma
.RI [ -e ] " " [ -r ] "<palette>" [ "<gamma>..." ]
.SH DESCRIPTION
.B vtgamma
allows you to set the gamma correction on Linux console.  It also works on
most terminal emulators as well.  A good deal of monitors tend to have
too dark blue -- human eye is far less sensitive to blue light.  This is
acceptable for photographic images that should look realistically, but
can cause blue, especially dark blue, text to be hard to read.

.B vtgamma
is also useful on aged CRT
monitors, which tend to rapidly lose the luminance-to-voltage ratio.  Even
after just 2-3 years, typical CRT often needs gamma of as much as 1.6 to
resemble a new one.  The author of this words has seen a specimen that
needed gamma of 2 2 6 (ie, with a big loss of blue) despite still having
sharp display.

Gamma correction is given as a positive floating-point number, with 1.0 being
the default.

You may also select a different palette than default "\fBvga\fR".  A palette
may then have a gamma correction applied to it -- all options are allowed.

.TP
This version recognizes the following palettes:

vga
.br
gruvbox
.br
monokai
.br
ubuntu

.RE
.RB "To affect the login prompt, it's best to: " "vtgamma"
.I 1.6
.BR ">>/etc/issue" ", where "
.IR 1.6 " is the gamma correction you want (but see \fB-p\fR)."

Without \fB-p\fR, the
color profile lasts either until the next time a program resets the terminal.
While this is quite a rare thing, it happens, and thus you'll probably want to
have the gamma refreshed every time a program exits.  The recommended way is
to include \fBvtgamma\fR in \fBPROMPT_COMMAND\fR:
.br
.HP
.I PROMPT_COMMAND='vtgamma 1.6'
.HP 0
although if you don't want to spawn a process every prompt, you may instead
edit
.B ~/.bashrc
and include the output of
.BI "vtgamma -e " 1.6
.RB "in " PS1 ", enclosed between " \(rs[ " and " \(rs] "."
Unfortunately, this won't work when you switch between terminals using
different ways of setting gamma (currently Linux console vs most graphical
terminals); \fBMidnight Commander\fR can't cope well with prompts
containing such codes either.
.SH OPTIONS
.TP
.BR -e | --escape
Escapes the codes in a form suitable for
.BR "echo -e" ","
C/Perl/... literals, etc.  You might want to include this in
\fB/etc/issue\fR.
.TP
.BR -p | --permanent
On Linux console (VT) only, sets the palette in a way that's permanent until
reboot.  This uses an ioctl rather than terminal codes, thus can't be
captured and written as a string.
.TP
.BR -r | --reverse
Black on white mode.  Note that this does what you'd expect only on certain
terminals, such as Linux console.  On most graphical terminal emulators this
affects only "real" black and white but not primary text and background
colors.
.TP
.BR -l | --lab | --Lab | --lchab | --LCHab
Uses the LCHab color space (a variant of Lab) instead of RGB, this allows
brightening colors above FF0000.  Requires the \fIGraphics::ColorObject\fR
library (on Debian, install \fIlibgraphics-colorobject-perl\fR).
.SH "SEE ALSO"
.IR xgamma ( 1 )
.SH AUTHOR
Both the program and this man page are the fault of Adam Borowski.  Both of
them are in the Public Domain, or the closest approximation allowed by law.
